<?php
if (session_status() === PHP_SESSION_NONE) session_start();
$languages = [
    'ru' => [
        'nav_catalog' => 'Каталог', 'nav_tradein' => 'Trade-in', 'nav_login' => 'Вход', 'nav_join' => 'Регистрация', 'nav_admin' => 'Панель', 'nav_profile' => 'Профиль', 'nav_exit' => 'Выход',
        'hero_1' => 'ЭСТЕТИКА',
'hero_2' => 'МЕХАНИКИ',
'hero_3' => 'И СТАТУСА', 'hero_p' => 'Проверенные автомобили. Прозрачная история. Юридический аудит.',
        'f_brand' => 'Марка', 'f_any' => 'Любая', 'f_price' => 'Цена до', 'btn_search' => 'Найти',
        'stat_1' => 'Лет опыта', 'stat_2' => 'Продано', 'stat_3' => 'Чистота', 'stat_4' => 'Сервис',
        'sec_popular' => 'Популярные <span>модели</span>', 'btn_all' => 'Весь каталог', 'btn_more' => 'Детали',
        'calc_h' => 'Рассчитать <span>кредит</span>', 'calc_p' => 'Стоимость', 'calc_d' => 'Взнос', 'calc_m' => 'Платеж', 'calc_btn' => 'Оформить заявку',
        'rev_h' => 'Голоса <span>клиентов</span>', 'spec_hp' => 'л.с.', 'spec_km' => 'км', 'spec_y' => 'г.',
        'spec_year' => 'ГОД ВЫПУСКА', 'spec_km_title' => 'ПРОБЕГ (КМ)', 'spec_power' => 'МОЩНОСТЬ', 'spec_trans' => 'ТРАНСМИССИЯ',
        'desc_title' => 'ОПИСАНИЕ ОБЪЕКТА', 'lead_title' => 'ПОЛУЧИТЬ ПРЕДЛОЖЕНИЕ', 'lead_btn' => 'ОТПРАВИТЬ ЗАЯВКУ', 'status_sold' => 'ПРОДАНО',
        'fav_save' => 'В ИЗБРАННОЕ', 'fav_saved' => 'В ИЗБРАННОМ',
        'credit_h' => 'ЗАЯВКА НА <span>КРЕДИТ</span>', 'credit_name' => 'ФИО ПОЛНОСТЬЮ', 'credit_phone' => 'ТЕЛЕФОН', 'credit_sum' => 'СУММА КРЕДИТА (₽)', 'credit_term' => 'СРОК (МЕС)', 'credit_success' => 'ОТПРАВЛЕНО', 'credit_back' => 'НА ГЛАВНУЮ',
        'eval_h' => 'TRADE-IN <span>ОЦЕНКА</span>', 'eval_p' => 'Заполните данные для оценки вашего авто.', 'eval_brand' => 'МАРКА', 'eval_model' => 'МОДЕЛЬ', 'eval_year' => 'ГОД', 'eval_km' => 'ПРОБЕГ', 'eval_phone' => 'ТЕЛЕФОН', 'eval_btn' => 'ОЦЕНИТЬ','sec_tradein' => 'TRADE-IN <span>ОЦЕНКА</span>',
'sec_testdrive' => 'ЗАПИСЬ НА <span>ТЕСТ-ДРАЙВ</span>',
'f_your_car' => 'ВАШ АВТОМОБИЛЬ (МАРКА, МОДЕЛЬ)',
'f_year' => 'ГОД',
'f_km' => 'ПРОБЕГ',
'f_phone' => 'ТЕЛЕФОН',
'f_select_car' => 'ВЫБЕРИТЕ АВТО ИЗ НАЛИЧИЯ',
'f_date' => 'ЖЕЛАЕМАЯ ДАТА',
'btn_send_request' => 'ОТПРАВИТЬ ЗАЯВКУ SEND','f_schedule' => 'ГРАФИК РАБОТЫ',
'f_work_days' => 'ПН-ВС 09:00 — 21:00',
'f_social' => 'МЫ В СЕТИ',
'f_copy' => 'Данный ресурс является объектом дипломного проектирования. Все данные носят ознакомительный характер.',
'f_privacy' => 'Политика конфиденциальности','sec_protocol' => 'ПРОТОКОЛ <span>ПРОВЕРКИ</span>',
'prot_sub' => 'Каждый объект проходит аудит по 150 контрольным точкам перед зачислением в сток.',
'prot_1_h' => 'Двигатель и КПП',
'prot_1_p' => 'Эндоскопия цилиндров, замер компрессии и компьютерная диагностика блоков управления.',
'prot_2_h' => 'Ходовая часть',
'prot_2_p' => 'Проверка геометрии подвески, состояния тормозной системы и герметичности узлов.',
'prot_3_h' => 'Кузовной аудит',
'prot_3_p' => 'Сканирование толщины ЛКП и проверка силовой структуры кузова на стапеле.',
'prot_4_h' => 'Юр. экспертиза',
'prot_4_p' => 'Проверка по базам ГИБДД, ФССП и реестрам залогов. 100% юридическая чистота.','adm_add_h' => 'ДОБАВИТЬ <span>ОБЪЕКТ</span>',
'adm_brand' => 'ПРОИЗВОДИТЕЛЬ',
'adm_model' => 'МОДЕЛЬ',
'adm_price' => 'ЦЕНА (₽)',
'adm_year' => 'ГОД ВЫПУСКА',
'adm_km' => 'ПРОБЕГ (КМ)',
'adm_hp' => 'МОЩНОСТЬ (HP)',
'adm_trans' => 'ТРАНСМИССИЯ',
'adm_desc' => 'ТЕХНИЧЕСКОЕ ОПИСАНИЕ',
'adm_img' => 'ГЛАВНОЕ ИЗОБРАЖЕНИЕ',
'adm_verified' => 'ПРОВЕРЕНО ЭКСПЕРТОМ',
'adm_owner' => '1 ВЛАДЕЛЕЦ',
'adm_send' => 'ЗАПИСАТЬ В РЕЕСТР', 'car_tech_specs' => 'ТЕХНИЧЕСКИЙ ПАСПОРТ',
'car_next' => 'СЛЕДУЮЩЕЕ',
'car_prev' => 'ПРЕДЫДУЩЕЕ', 'prot_1_p' => 'Эндоскопическое исследование цилиндров, замер компрессии и полная компьютерная диагностика электронных блоков управления (ЭБУ) на наличие скрытых архивных ошибок.',
'prot_2_p' => 'Проверка геометрии подвески на 3D-стенде, аудит состояния тормозной системы, замер износа дисков и проверка герметичности всех гидравлических узлов и агрегатов.',
'prot_3_p' => 'Ультразвуковое сканирование толщины лакокрасочного покрытия всех панелей и детальная проверка заводских швов и силовой структуры кузова на наличие деформаций.',
'prot_4_p' => 'Многоуровневая проверка по базам ГИБДД, ФССП и банковским реестрам залогов. Подтверждение оригинальности VIN-номера и юридической чистоты всех документов.', 
'form_tradein_h' => 'TRADE-IN <span>ОЦЕНКА</span>',
'form_testdrive_h' => 'ЗАПИСЬ НА <span>ТЕСТ-ДРАЙВ</span>',
'ph_your_car' => 'ВАШ АВТОМОБИЛЬ (МАРКА, МОДЕЛЬ)',
'ph_year' => 'ГОД',
'ph_km' => 'ПРОБЕГ',
'ph_phone' => 'ТЕЛЕФОН +7',
'ph_select_car' => 'ВЫБЕРИТЕ АВТО ИЗ НАЛИЧИЯ',
'btn_send' => 'ОТПРАВИТЬ ЗАЯВКУ',
'btn_book' => 'ЗАПИСАТЬСЯ', 'nav_reviews' => 'Отзывы',
'rev_title' => 'ГОЛОСА <span>КЛИЕНТОВ</span>',
'rev_subtitle' => 'Опыт владения и обслуживания Верифицированные отчеты',
'rev_write_h' => 'ОСТАВИТЬ ОТЗЫВ',
'rev_car_info' => 'АВТОМОБИЛЬ (МАРКА, МОДЕЛЬ)',
'rev_rating' => 'ВАША ОЦЕНКА',
'rev_text' => 'ТЕКСТ ОТЗЫВА',
'rev_submit' => 'ОПУБЛИКОВАТЬ',
'rev_success' => 'ОТЗЫВ ОТПРАВЛЕН НА МОДЕРАЦИЮ.',
'rev_auth_req' => 'Чтобы оставить отзыв, пожалуйста, <a href="login.php">войдите</a>.',

        // Навигация
        'nav_catalog' => 'Каталог', 'nav_tradein' => 'Trade-in', 'nav_reviews' => 'Отзывы', 'nav_login' => 'Вход', 'nav_join' => 'Регистрация', 'nav_admin' => 'Панель', 'nav_profile' => 'Профиль', 'nav_exit' => 'Выход',
        // Заголовки отзывов
        'rev_title' => 'ГОЛОСА <span>КЛИЕНТОВ</span>',
        'rev_subtitle' => 'Опыт владения и обслуживания Верифицированные отчеты',
        'rev_write_h' => 'ОСТАВИТЬ <span>ОТЗЫВ</span>',
        'rev_write_p' => 'Ваш отзыв будет опубликован после проверки модератором.',
        // Поля формы
        'rev_field_car' => 'КУПЛЕННЫЙ АВТОМОБИЛЬ',
        'rev_field_rating' => 'ОЦЕНКА СЕРВИСА',
        'rev_field_text' => 'ВАШ КОММЕНТАРИЙ',
        'rev_btn_send' => 'ОТПРАВИТЬ ОТЗЫВ',
        'rev_success' => 'СПАСИБО! ОТЗЫВ ОТПРАВЛЕН НА МОДЕРАЦИЮ.',
        // Характеристики
        'spec_hp' => 'л.с.', 'spec_km' => 'км', 'spec_y' => 'г.',
        // Остальное
        'hero_p' => 'Проверенные автомобили. Прозрачная история. Юридический аудит.',
        'status_sold' => 'ПРОДАНО', 'rev_title' => 'ГОЛОСА <span>КЛИЕНТОВ</span>',
        'rev_subtitle' => 'Опыт владения и обслуживания Верифицированные отчеты',
        'rev_write_h' => 'ОСТАВИТЬ <span>ОТЗЫВ</span>',
        'rev_write_p' => 'Ваш отзыв будет опубликован после проверки модератором.',
        'rev_field_car' => 'КУПЛЕННЫЙ АВТОМОБИЛЬ',
        'rev_field_rating' => 'ОЦЕНКА СЕРВИСА',
        'rev_field_text' => 'ВАШ КОММЕНТАРИЙ',
        'rev_btn_send' => 'ОТПРАВИТЬ ОТЗЫВ',
        'rev_success' => 'СПАСИБО! ОТЗЫВ ОТПРАВЛЕН НА МОДЕРАЦИЮ.', 'nav_compare' => 'Сравнение',
'btn_compare' => 'СРАВНИТЬ',
'comp_h' => 'СРАВНЕНИЕ <span>ОБЪЕКТОВ</span>',
'comp_empty' => 'СПИСОК СРАВНЕНИЯ ПУСТ',
'comp_remove' => 'УДАЛИТЬ', 'ser_leasing' => 'Лизинг',
'ser_installments' => 'Рассрочка 0%',
'ser_delivery' => 'Доставка в регионы',
'ser_booking' => 'Бронирование',
'btn_book_now' => 'ЗАБРОНИРОВАТЬ',
'msg_booked' => 'ОБЪЕКТ ЗАБРОНИРОВАН',
'trust_rating' => 'РЕЙТИНГ ДИЛЕРА',         'auth_login_h' => 'USER <span>LOGIN</span>',
'auth_reg_h' => 'CREATE <span>ACCOUNT</span>',
'auth_login_btn' => 'АВТОРИЗОВАТЬСЯ',
'auth_reg_btn' => 'СОЗДАТЬ АККАУНТ',
'auth_no_account' => 'Нет аккаунта?',
'auth_has_account' => 'Уже есть аккаунт?', 'adm_inventory_h' => 'УПРАВЛЕНИЕ <span>СКЛАДОМ</span>',
'adm_inventory_sub' => 'Реестр всех объектов в базе данных',
'adm_btn_delete' => 'УДАЛИТЬ ОБЪЕКТ',
'adm_confirm_delete' => 'ВЫ УВЕРЕНЫ, ЧТО ХОТИТЕ УДАЛИТЬ ЭТОТ ОБЪЕКТ ИЗ БАЗЫ?', 'car_equipment' => 'КОМПЛЕКТАЦИЯ',
'car_tech_data' => 'ТЕХНИЧЕСКИЕ ДАННЫЕ',
'spec_engine' => 'ДВИГАТЕЛЬ',
'spec_drive' => 'ПРИВОД',
'spec_fuel' => 'ТОПЛИВО',
'spec_owners' => 'ВЛАДЕЛЬЦЕВ', 'adm_users_h' => 'УПРАВЛЕНИЕ <span>ПОЛЬЗОВАТЕЛЯМИ</span>',
'adm_users_sub' => 'Реестр учетных записей Назначение ролей и контроль доступа',
'u_role' => 'РОЛЬ',
'u_status' => 'СТАТУС',
'u_action' => 'ДЕЙСТВИЕ',
'btn_block' => 'БЛОКИРОВАТЬ',
'btn_unblock' => 'РАЗБЛОКИРОВАТЬ', 
'st_1_h' => 'ПРОЗРАЧНОСТЬ',
'st_1_p' => 'Полная история владения и обслуживания.',
'st_2_h' => 'ВАЛИДАЦИЯ',
'st_2_p' => 'Проверка каждого объекта экспертом.',
'st_3_h' => 'БЕЗОПАСНОСТЬ',
'st_3_p' => 'Шифрование данных и чистота сделки.',
'st_4_h' => 'СКОРОСТЬ',
'st_4_p' => 'Обработка заявок в режиме реального времени.',
    ],
    'en' => [
        'nav_catalog' => 'Inventory', 'nav_tradein' => 'Trade-in', 'nav_login' => 'Login', 'nav_join' => 'Join', 'nav_admin' => 'Admin', 'nav_profile' => 'Profile', 'nav_exit' => 'Logout',
        'hero_1' => 'AESTHETICS',
'hero_2' => 'OF MECHANICS',
'hero_3' => '& STATUS', 'hero_p' => 'Verified vehicles. Transparent history. Legal audit.',
        'f_brand' => 'Brand', 'f_any' => 'Any', 'f_price' => 'Max Price', 'btn_search' => 'Search',
        'stat_1' => 'Years Exp.', 'stat_2' => 'Units Sold', 'stat_3' => 'Legal Clear', 'stat_4' => 'Service',
        'sec_popular' => 'Popular <span>Models</span>', 'btn_all' => 'View All', 'btn_more' => 'Details',
        'calc_h' => 'Credit <span>Calculator</span>', 'calc_p' => 'Price', 'calc_d' => 'Downpayment', 'calc_m' => 'Monthly', 'calc_btn' => 'Apply Now',
        'rev_h' => 'Client <span>Voices</span>', 'spec_hp' => 'hp', 'spec_km' => 'km', 'spec_y' => 'y.',
        'spec_year' => 'YEAR', 'spec_km_title' => 'MILEAGE (KM)', 'spec_power' => 'POWER', 'spec_trans' => 'TRANSMISSION',
        'desc_title' => 'OBJECT DESCRIPTION', 'lead_title' => 'GET AN OFFER', 'lead_btn' => 'SEND REQUEST', 'status_sold' => 'SOLD OUT',
        'fav_save' => 'SAVE TO FAV', 'fav_saved' => 'SAVED',
        'credit_h' => 'CREDIT <span>APPLICATION</span>', 'credit_name' => 'FULL NAME', 'credit_phone' => 'PHONE', 'credit_sum' => 'SUM (₽)', 'credit_term' => 'TERM (MO)', 'credit_success' => 'SENT', 'credit_back' => 'BACK HOME',
        'eval_h' => 'TRADE-IN <span>VALUATION</span>', 'eval_p' => 'Enter vehicle data for valuation.', 'eval_brand' => 'BRAND', 'eval_model' => 'MODEL', 'eval_year' => 'YEAR', 'eval_km' => 'MILEAGE', 'eval_phone' => 'PHONE', 'eval_btn' => 'VALUATE','sec_tradein' => 'TRADE-IN <span>VALUATION</span>',
'sec_testdrive' => 'SCHEDULE <span>TEST DRIVE</span>',
'f_your_car' => 'YOUR CAR (BRAND, MODEL)',
'f_year' => 'YEAR',
'f_km' => 'MILEAGE',
'f_phone' => 'PHONE',
'f_select_car' => 'SELECT CAR FROM STOCK',
'f_date' => 'PREFERRED DATE',
'btn_send_request' => 'SEND APPLICATION SEND', 'f_schedule' => 'WORKING HOURS',
'f_work_days' => 'MON-SUN 09:00 — 21:00',
'f_social' => 'SOCIAL MEDIA',
'f_copy' => 'This resource is a diploma project object. All data is for informational purposes only.',
'f_privacy' => 'Privacy Policy', 'sec_protocol' => 'DIAGNOSTIC <span>PROTOCOL</span>',
'prot_sub' => 'Every unit undergoes a 150-point technical audit before entering the inventory.',
'prot_1_h' => 'Engine & Transmission',
'prot_1_p' => 'Cylinder endoscopy, compression testing, and ECU electronic diagnostics.',
'prot_2_h' => 'Chassis & Suspension',
'prot_2_p' => 'Suspension geometry check, braking system analysis, and component integrity.',
'prot_3_h' => 'Body & Paint Audit',
'prot_3_p' => 'Paint thickness scanning and structural integrity verification.',
'prot_4_h' => 'Legal Expertise',
'prot_4_p' => 'Verification against police databases, bailiff records, and lien registries.', 'adm_add_h' => 'ADD <span>NEW UNIT</span>',
'adm_brand' => 'MANUFACTURER',
'adm_model' => 'MODEL NAME',
'adm_price' => 'PRICE (RUB)',
'adm_year' => 'PRODUCTION YEAR',
'adm_km' => 'MILEAGE (KM)',
'adm_hp' => 'POWER (HP)',
'adm_trans' => 'TRANSMISSION',
'adm_desc' => 'TECHNICAL DESCRIPTION',
'adm_img' => 'MAIN OBJECT IMAGE',
'adm_verified' => 'VERIFIED BY EXPERT',
'adm_owner' => '1 OWNER',
'adm_send' => 'SAVE TO DATABASE', 'car_tech_specs' => 'TECHNICAL SPECIFICATIONS',
'car_next' => 'NEXT',
'car_prev' => 'PREVIOUS', 'prot_1_p' => 'Full cylinder endoscopy, compression testing, and deep computer diagnostics of electronic control units (ECU) for hidden fault codes and history logs.',
'prot_2_p' => '3D suspension geometry check, comprehensive brake system analysis, disk wear measurement, and fluid leakage inspection for all mechanical units.',
'prot_3_p' => 'Ultrasonic paint thickness scanning across all panels and structural frame integrity verification to detect any hidden past repairs or deformations.',
'prot_4_p' => 'Multi-level verification against police databases, bailiff records, and bank lien registries. VIN originality confirmation and full legal paperwork audit.', 

'form_tradein_h' => 'TRADE-IN <span>VALUATION</span>',
'form_testdrive_h' => 'SCHEDULE <span>TEST-DRIVE</span>',
'ph_your_car' => 'YOUR VEHICLE (BRAND, MODEL)',
'ph_year' => 'YEAR',
'ph_km' => 'MILEAGE',
'ph_phone' => 'PHONE +7',
'ph_select_car' => 'SELECT CAR FROM STOCK',
'btn_send' => 'SEND REQUEST',
'btn_book' => 'BOOK NOW', 'nav_reviews' => 'Reviews',
'rev_title' => 'CLIENT <span>VOICES</span>',
'rev_subtitle' => 'Ownership and service experience Verified reports',
'rev_write_h' => 'WRITE A REVIEW',
'rev_car_info' => 'VEHICLE (BRAND, MODEL)',
'rev_rating' => 'YOUR RATING',
'rev_text' => 'REVIEW CONTENT',
'rev_submit' => 'POST REVIEW',
'rev_success' => 'REVIEW SENT FOR MODERATION.',
'rev_auth_req' => 'To leave a review, please <a href="login.php">login</a>.',
'nav_catalog' => 'Inventory', 'nav_tradein' => 'Trade-in', 'nav_reviews' => 'Reviews', 'nav_login' => 'Login', 'nav_join' => 'Join', 'nav_admin' => 'Admin', 'nav_profile' => 'Profile', 'nav_exit' => 'Logout',
'rev_title' => 'CLIENT <span>VOICES</span>',
'rev_subtitle' => 'Ownership and service experience Verified reports',
'rev_write_h' => 'WRITE <span>A REVIEW</span>',
'rev_write_p' => 'Your review will be published after moderator approval.',
'rev_field_car' => 'PURCHASED VEHICLE',
'rev_field_rating' => 'SERVICE RATING',
'rev_field_text' => 'YOUR COMMENT',
'rev_btn_send' => 'SUBMIT REVIEW',
'rev_success' => 'THANK YOU! REVIEW SUBMITTED FOR MODERATION.',
'spec_hp' => 'hp', 'spec_km' => 'km', 'spec_y' => 'y.',
'hero_p' => 'Verified vehicles. Transparent history. Legal audit.',
'status_sold' => 'SOLD OUT', 'rev_title' => 'CLIENT <span>VOICES</span>',
'rev_subtitle' => 'Ownership experience Verified reports',
'rev_write_h' => 'WRITE <span>A REVIEW</span>',
'rev_write_p' => 'Your review will be published after moderator approval.',
'rev_field_car' => 'PURCHASED VEHICLE',
'rev_field_rating' => 'SERVICE RATING',
'rev_field_text' => 'YOUR COMMENT',
'rev_btn_send' => 'SUBMIT REVIEW',
'rev_success' => 'THANK YOU! REVIEW SUBMITTED FOR MODERATION.', 'nav_compare' => 'Compare',
'btn_compare' => 'COMPARE',
'comp_h' => 'UNIT <span>COMPARISON</span>',
'comp_empty' => 'COMPARISON LIST IS EMPTY',
'comp_remove' => 'REMOVE', 'ser_leasing' => 'Leasing',
'ser_installments' => '0% Installments',
'ser_delivery' => 'Region Delivery',
'ser_booking' => 'Online Booking',
'btn_book_now' => 'BOOK OBJECT',
'msg_booked' => 'OBJECT IS RESERVED',
'trust_rating' => 'DEALER RATING',         'auth_login_h' => 'USER <span>LOGIN</span>',
'auth_reg_h' => 'CREATE <span>ACCOUNT</span>',
'auth_login_btn' => 'AUTHORIZE',
'auth_reg_btn' => 'CREATE',
'auth_no_account' => 'No account?',
'auth_has_account' => 'Have an account?', 'adm_inventory_h' => 'INVENTORY <span>MANAGEMENT</span>',
'adm_inventory_sub' => 'Database records of all units ',
'adm_btn_delete' => 'DELETE OBJECT',
'adm_confirm_delete' => 'ARE YOU SURE YOU WANT TO REMOVE THIS UNIT FROM DATABASE?', 'car_equipment' => 'EQUIPMENT',
'car_tech_data' => 'TECHNICAL DATA',
'spec_engine' => 'ENGINE VOLUME',
'spec_drive' => 'DRIVE TYPE',
'spec_fuel' => 'FUEL TYPE',
'spec_owners' => 'OWNERS', 'adm_users_h' => 'USER <span>MANAGEMENT</span>',
'adm_users_sub' => 'Account registry Role assignment and access control',
'u_role' => 'ROLE',
'u_status' => 'STATUS',
'u_action' => 'ACTION',
'btn_block' => 'BLOCK',
'btn_unblock' => 'UNBLOCK', 'st_1_h' => 'TRANSPARENCY',
'st_1_p' => 'Full ownership and service history.',
'st_2_h' => 'VALIDATION',
'st_2_p' => 'Expert verification of every unit.',
'st_3_h' => 'SECURITY',
'st_3_p' => 'Data encryption and legal safety.',
'st_4_h' => 'EFFICIENCY',
'st_4_p' => 'Real-time application processing.',
    ]
];
if (isset($_GET['lang']) && array_key_exists($_GET['lang'], $languages)) $_SESSION['lang'] = $_GET['lang'];
$ln = $_SESSION['lang'] ?? 'ru';
$txt = $languages[$ln];